# omniauth_keys:
#   facebook:
#      token:  '513194658757456’'
#      secret:    '17087499d8baee97t279b09ae0971fcf'
#     scope:  'user_about_me, export_stream, publish_stream, publish_actions, email, user_photos, friends_photos, read_stream, user_birthday'
#   twitter:
#     token:  'rR39c7DLg9uPMNuRpvcCA'
#     secret:    'a0BvlmX8uel9N8qgc0Zr7TzS9haqbmcScXwlr3bzCPA'
#   instagram:
#     token:  '36eba2b3c4d146cc9r1801d013a0d6af'
#     secret:    'bbfe132fd0394ed7648e0d9be5c91a73'